version: "2.4"

services:
  sut:
    image: alpine:3.18
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-container-jail}
      COMPOSE_FILE: docker-compose.yml:docker-compose.test.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/src/app:ro
    working_dir: /usr/src/app
    depends_on:
      - alpine-test
      - debian-test
      - ubuntu-test
    command:
      - /bin/sh
      - -c
      - |
        set -ex
        apk add --no-cache docker-cli-compose

        counter=0
        while ! docker compose logs alpine-test | grep -q "healthcheck.sh exited with status 0"; do
          sleep 3
          counter=$$((counter+1))
          if [ $$counter -gt 30 ]; then
            exit 1
          fi
        done

        counter=0
        while ! docker compose logs debian-test | grep -q "healthcheck.sh exited with status 0"; do
          sleep 3
          counter=$$((counter+1))
          if [ $$counter -gt 30 ]; then
            exit 1
          fi
        done

        counter=0
        while ! docker compose logs ubuntu-test | grep -q "healthcheck.sh exited with status 0"; do
          sleep 3
          counter=$$((counter+1))
          if [ $$counter -gt 30 ]; then
            exit 1
          fi
        done

  alpine-test:
    extends:
      file: docker-compose.yml
      service: jailer
    build:
      args:
        TEST_IMAGE: alpine:3.18
      cache_from:
        - sut:latest
    hostname: alpine-test

  debian-test:
    extends:
      file: docker-compose.yml
      service: jailer
    build:
      args:
        TEST_IMAGE: debian:bookworm-slim
      cache_from:
        - sut:latest
    hostname: debian-test

  ubuntu-test:
    extends:
      file: docker-compose.yml
      service: jailer
    build:
      args:
        TEST_IMAGE: ubuntu:jammy
      cache_from:
        - sut:latest
    hostname: ubuntu-test
