version: "2.4"

services:
  sut:
    image: alpine:3.18
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-ctr-jailer}
      COMPOSE_FILE: docker-compose.yml:docker-compose.test.yml
    depends_on:
      - alpine-test
      - debian-test
      - ubuntu-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/src/app:ro
    working_dir: /usr/src/app
    command:
      - /bin/sh
      - -c
      - |
        set -ex
        apk add --no-cache docker-cli-compose

        count=0
        while true; do

          if [ $$count -gt 10 ]; then
            echo "Timed out waiting for healthchecks to pass"
            exit 1
          fi

          count=$$(($$count + 1))

          sleep 3
          
          docker compose logs --no-color alpine-test | grep "touch /mnt/data/healthy" || continue
          docker compose logs --no-color debian-test | grep "touch /mnt/data/healthy" || continue
          docker compose logs --no-color ubuntu-test | grep "touch /mnt/data/healthy" || continue

          break

        done

  alpine-test:
    extends:
      file: docker-compose.yml
      service: firecracker
    build:
      context: .
      target: alpine-test
    command: /usr/local/bin/healthcheck.sh

  debian-test:
    extends:
      file: docker-compose.yml
      service: firecracker
    build:
      context: .
      target: debian-test
    command: /usr/local/bin/healthcheck.sh

  ubuntu-test:
    extends:
      file: docker-compose.yml
      service: firecracker
    build:
      context: .
      target: ubuntu-test
    command: /usr/local/bin/healthcheck.sh
