version: "2.4"

services:
  jailer:
    build: .
    # Privileged is required to setup the rootfs and jailer
    # but permissions are dropped to a chroot in order to start your VM
    privileged: true
    network_mode: host
    # Optionally run the VM jail in-memory to save storage wear
    tmpfs:
      - /tmp
      - /run
      - /srv
