version: "2.4"

services:
  sut:
    image: alpine:3.18
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-ctr-jailer}
      COMPOSE_FILE: docker-compose.yml:docker-compose.test.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/src/app:ro
    working_dir: /usr/src/app
    command:
      - /bin/sh
      - -c
      - |
        set -ex
        apk add --no-cache docker-cli-compose

        docker compose run --rm --remove-orphans alpine-test | tee /dev/stderr | grep "touch /mnt/data/healthy"

        docker compose run --rm --remove-orphans debian-test | tee /dev/stderr | grep "touch /mnt/data/healthy"

        docker compose run --rm --remove-orphans ubuntu-test | tee /dev/stderr | grep "touch /mnt/data/healthy"

        docker compose run --rm --remove-orphans dind-test | tee /dev/stderr | grep "Daemon has completed initialization"

  alpine-test:
    extends:
      file: docker-compose.yml
      service: firecracker
    build:
      context: .
      target: alpine-test
    hostname: alpine-test

  debian-test:
    extends:
      file: docker-compose.yml
      service: firecracker
    build:
      context: .
      target: debian-test
    hostname: debian-test

  ubuntu-test:
    extends:
      file: docker-compose.yml
      service: firecracker
    build:
      context: .
      target: ubuntu-test
    hostname: ubuntu-test

  dind-test:
    extends:
      file: docker-compose.yml
      service: firecracker
    build:
      context: .
      target: dind-test
    environment:
      - DOCKER_TLS_CERTDIR=
    command:
      - sh
      - -c
      - /usr/local/bin/dockerd-entrypoint.sh & sleep 60
    hostname: dind-test
