version: "2.4"

services:
  sut:
    image: alpine:3.18
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-ctr-jailer}
      COMPOSE_FILE: docker-compose.yml:docker-compose.test.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/src/app:ro
    working_dir: /usr/src/app
    depends_on:
      - alpine-test
      - debian-test
      - ubuntu-test
      - dind-test
    command:
      - /bin/sh
      - -c
      - |
        set -ex
        apk add --no-cache docker-cli-compose

        counter=0
        while ! docker compose logs alpine-test | grep -q "Hello, World!"; do
          sleep 3
          counter=$$((counter+1))
          if [ $$counter -gt 20 ]; then
            exit 1
          fi
        done

        counter=0
        while ! docker compose logs debian-test | grep -q "Hello, World!"; do
          sleep 3
          counter=$$((counter+1))
          if [ $$counter -gt 20 ]; then
            exit 1
          fi
        done

        counter=0
        while ! docker compose logs ubuntu-test | grep -q "Hello, World!"; do
          sleep 3
          counter=$$((counter+1))
          if [ $$counter -gt 20 ]; then
            exit 1
          fi
        done

        counter=0
        while ! docker compose logs dind-test | grep -q "Daemon has completed initialization"; do
          sleep 3
          counter=$$((counter+1))
          if [ $$counter -gt 20 ]; then
            exit 1
          fi
        done

  alpine-test:
    extends:
      file: docker-compose.yml
      service: jailer
    build:
      context: .
      target: alpine-test
      cache_from:
        - sut:latest
    hostname: alpine-test

  debian-test:
    extends:
      file: docker-compose.yml
      service: jailer
    build:
      context: .
      target: debian-test
      cache_from:
        - sut:latest
    hostname: debian-test

  ubuntu-test:
    extends:
      file: docker-compose.yml
      service: jailer
    build:
      context: .
      target: ubuntu-test
      cache_from:
        - sut:latest
    hostname: ubuntu-test

  dind-test:
    extends:
      file: docker-compose.yml
      service: jailer
    build:
      context: .
      target: dind-test
      cache_from:
        - sut:latest
    environment:
      - DOCKER_TLS_CERTDIR=
    command:
      - sh
      - -c
      - /usr/local/bin/dockerd-entrypoint.sh & sleep 30 ; docker run hello-world
    hostname: dind-test
