#!/bin/sh

exec 1>/dev/console
exec 2>/dev/console

chown root:tty /dev/console
chmod 622 /dev/console

# create symlink to /proc/self/fd
ln -s /proc/self/fd /dev/fd

ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

# Mount essential file systems
if ! mountpoint -q /proc; then
  mkdir -p /proc
  mount -v -t proc none /proc
fi

if ! mountpoint -q /sys; then
  mkdir -p /sys
  mount -v -t sysfs none /sys
fi

if ! mountpoint -q /dev; then
  mkdir -p /dev
  mount -v -t devtmpfs none /dev
fi

if ! mountpoint -q /tmp; then
  mkdir -p /tmp
  mount -v -t tmpfs none /tmp
fi

if ! mountpoint -q /run; then
  mkdir -p /run
  mount -v -t tmpfs none /run
  ln -sf /run /var/run
fi

if ! mountpoint -q /dev/shm; then
  mkdir -p /dev/shm
  mount -v -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=65536k shm /dev/shm
fi

if ! mountpoint -q /sys/fs/cgroup; then
  mkdir -p /sys/fs/cgroup
  # mount -v -t cgroup cgroup /sys/fs/cgroup
  mount -v -t tmpfs cgroup_root /sys/fs/cgroup
fi

# Create the cgroup hierarchy
for d in cpuset cpu cpuacct blkio memory devices freezer net_cls perf_event net_prio hugetlb pids; do
  if [ ! -d /sys/fs/cgroup/"$d" ]; then
    mkdir -p /sys/fs/cgroup/"$d"
    mount -v -t cgroup -o "$d" cgroup /sys/fs/cgroup/"$d"
  fi
done

# Mount the cgroup hierarchy for systemd
if [ ! -d /sys/fs/cgroup/systemd ]; then
  mkdir -p /sys/fs/cgroup/systemd
  mount -v -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
fi

if ! grep -q localhost /etc/hosts; then
  echo "127.0.0.1 localhost" >>/etc/hosts
fi

if [ -f /var/environment ]; then
  set -a
  # shellcheck disable=SC1091
  . /var/environment
  set +a
fi

# clear this file after export in case it contained secrets
rm -f /var/environment

# this is present in most base images to set up the environment
if [ -f /etc/profile ]; then
  # shellcheck disable=SC1091
  . /etc/profile || true
fi

# this is where ubuntu base images set PATH
if [ -f /etc/environment ]; then
  set -a
  # shellcheck disable=SC1091
  . /etc/environment
  set +a
fi
