#!/bin/sh

exec 1>/dev/console
exec 2>/dev/console

# Mount essential file systems
if ! mountpoint -q /proc; then
  mount -t proc none /proc
fi

if ! mountpoint -q /sys; then
  mount -t sysfs none /sys
fi

if ! mountpoint -q /dev; then
  mount -t devtmpfs none /dev
fi

if ! mountpoint -q /tmp; then
  mount -t tmpfs none /tmp
fi

if ! mountpoint -q /run; then
  mount -t tmpfs none /run
fi

# shellcheck disable=SC1091
. /etc/profile || true
