#!/bin/sh

exec 1>/dev/console
exec 2>/dev/console

chown root:tty /dev/console
chmod 622 /dev/console

ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

# Mount essential file systems
if ! mountpoint -q /proc; then
  mount -t proc none /proc
fi

if ! mountpoint -q /sys; then
  mount -t sysfs none /sys
fi

if ! mountpoint -q /dev; then
  mount -t devtmpfs none /dev
fi

if ! mountpoint -q /tmp; then
  mount -t tmpfs none /tmp
fi

if ! mountpoint -q /run; then
  mount -t tmpfs none /run
fi

if ! mountpoint -q /dev/shm; then
  mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=65536k shm /dev/shm
fi

if ! mountpoint -q /sys/fs/cgroup; then
  mount -t cgroup cgroup /sys/fs/cgroup
fi

if ! grep -q localhost /etc/hosts; then
  echo "127.0.0.1 localhost" >>/etc/hosts
fi

if [ -f /etc/profile ]; then
  # shellcheck disable=SC1091
  . /etc/profile || true
  rm -f /etc/profile.d/fc_exports.sh
fi
